### ISSUE TITLE
HV will crash if  launch two UOS with same UUID

### ISSUE THREAD

**Issue by lonzoc** [projectacrn/acrn-hypervisor#2984] opened 2019-04-19 07:46 UTC
HV will crash if launch two UOS with same UUID

**Comment by Mingyuan18** [comment] 2019-04-22 07:13
[External_System_ID] ACRN-3459

**Comment by fyin1** [comment] 2019-04-22 07:21
It's invalid to use same UUID for two different UOS. I believe this is expected behavior.

**Comment by gvancuts** [comment] 2019-04-29 14:45
I don't thing the hypervisor crashing can be considered a valid behaviour, this ought to be fixed in my opinion.

**Comment by Mingyuan18** [comment] 2019-05-09 05:47
@lonzoc , The patch is merge, Please help to confirm the result. Thanks!

**Comment by Mingyuan18** [comment] 2019-05-15 09:04
@lonzoc , We have verified it and the issue has been fixed. Could you please help to confirm it?

**Comment by fuzhongl** [comment] 2019-05-29 07:51
@lonzoc 
Patch was merged in CL 29400, please help to verify this issue; if fixed, please close this issue.
Any more concern, please update the comments. If no more feedback within two weeks, this ticket will be closed by default. 
You can reopen it if this issue can be reproduced for new release.
Appreciated for your understanding.

**Comment by Mingyuan18** [comment] 2019-06-11 08:06
Close this issue due to no any feedback in two weeks.

**Closed by Mingyuan18** 2019-06-11 08:06 UTC
Labels: priority: P3-Medium, status: Assigned, type: bug
