### ISSUE TITLE
Cursor not work when enable_initial_modeset is 0

### ISSUE THREAD

**Issue by zhipenggong** [projectacrn/acrn-hypervisor#1171] opened 2018-09-06 03:41 UTC
ddb allocation for the PLANE_CURSOR is removed to save some ddb for support 4K monitors. as a result, cursor not work when enable_initial_modeset is 0.

**Comment by mwang106** [comment] 2018-09-18 05:35
[External_System_ID] 255419

**Comment by dandanyx** [comment] 2018-10-16 05:31
Cannot reproduce this issue on WW42 AaaG build, and cursor can move normally.
Suggest to close this issue, thanks!

**Closed** 2018-10-16 05:46 UTC
Labels: status: open, type: bug
