### ISSUE TITLE
support RTCTv2

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6020] opened 2021-05-17 02:47 UTC
The hypervisor and device module shall be able to support both RTCTv1 and RTCTv2 for pre or post-launched RTVM.

**Comment by yonghuah** [comment] 2021-05-17 02:47
[External_System_ID] ACRN-7144

**Comment by NanlinXie** [comment] 2022-03-24 13:22
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:22 UTC
