### ISSUE TITLE
[ADL-S][Acrntrace]failed to run acrntrace test

### ISSUE THREAD

**Issue by lifeix** [projectacrn/acrn-hypervisor#6572] opened 2021-09-15 08:21 UTC
[External_System_ID] ACRN-7282

**Comment by wenlingz** [comment] 2021-09-16 00:47
[External_System_ID] ACRN-7282

**Comment by NanlinXie** [comment] 2022-03-24 13:12
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:12 UTC
Labels: status: new
