### ISSUE TITLE
Compilation error when enabling one Kata VM with the `sdc2` scenario

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#4040] opened 2019-11-08 08:32 UTC
If you set `CONFIG_MAX_KATA_VM_NUM=1` and try to compile using `make all BOARD=nuc7i7dnb SCENARIO=sdc2`, you get the following error message:
```
/usr/bin/bash scripts/genld.sh bsp/ld/link_ram.ld.in /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/link_ram.ld /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/.config
gcc -Wl,-Map=/home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/acrn.map -o /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/acrn.out  -Wl,--gc-sections -nostartfiles -nostdlib -Wl,-n,-z,max-page-size=0x1000 -pie -z noreloc-overflow   -T/home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/link_ram.ld \
	-Wl,--start-group /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/lib_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/boot_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/hw_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/vp_base_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/vp_dm_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/vp_trusty_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/vp_hcall_mod.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/libdebug.a /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/modules/sys_init_mod.a -Wl,--end-group
/usr/bin/ld: /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/acrn.out section `.bss' will not fit in region `ram'
/usr/bin/ld: region `ram' overflowed by 15429240 bytes
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:474: /home/gvancuts/work/acrn/acrn-hypervisor/build/hypervisor/acrn.out] Error 1
make[1]: Leaving directory '/home/gvancuts/work/acrn/acrn-hypervisor/hypervisor'
make: *** [Makefile:82: hypervisor] Error 2
```

**Comment by fuzhongl** [comment] 2020-05-04 07:28
@gvancuts By design, only SDC supports Kata VM.
Will close this git issue now, if you really need SDC2 to supports Kata VM; please check with @terryzouhao 
Thanks!

**Closed by fuzhongl** 2020-05-04 07:28 UTC
