### ISSUE TITLE
Current HV_RAM_SIZE calculation algrithom sometimes cause build failure

### ISSUE THREAD

**Issue by lifeix** [projectacrn/acrn-hypervisor#6663] opened 2021-10-13 03:24 UTC
[External_System_ID] ACRN-7390

**Comment by wenlingz** [comment] 2021-10-13 06:46
[External_System_ID] ACRN-7390

**Comment by gvancuts** [comment] 2021-11-03 09:27
This seems to have served as well to remove the `hvlog` parameter from the code. This implies some documentation needs to be updated, at least the `kernel-parameters.rst` and `hld-trace-log.rst` documents.

**Comment by NanlinXie** [comment] 2021-11-08 01:58
We didn't remove this function, we just remove default configuration in XML file, thus there's no need to update document.

**Comment by NanlinXie** [comment] 2022-03-24 13:11
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:11 UTC
Labels: status: new, doc: no doc needed
