### ISSUE TITLE
config-tools: Obsolete terms cleanup for SSRAM

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6012] opened 2021-05-14 06:03 UTC
Update as below:

PSRAM -> SSRAM
PTCT -> RTCT

CONFIG_PSRAM_ENABLED ===> CONFIG_SSRAM_ENABLED

**Comment by yonghuah** [comment] 2021-05-14 06:04
[External_System_ID] ACRN-7137

**Comment by NanlinXie** [comment] 2022-03-24 13:22
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:22 UTC
Labels: status: new
