### ISSUE TITLE
expose PMC to RTVM for RT profiling/tuning

### ISSUE THREAD

**Issue by mgcao** [projectacrn/acrn-hypervisor#6307] opened 2021-07-19 06:34 UTC
PMC is a general feature for RT profiling / tuning. Now for RTVM (core partition), always an offline patch needed for this feature.

It is better we can upstream/merge this patch.

**Comment by mgcao** [comment] 2021-07-27 01:49
[External_System_ID] ACRN-7312

**Comment by NanlinXie** [comment] 2022-03-24 13:18
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:18 UTC
