### ISSUE TITLE
don't force http.sslVerify to be false in ClearLinux docker

### ISSUE THREAD

**Issue by jren1** [projectacrn/acrn-hypervisor#659] opened 2018-07-10 23:03 UTC
In https://github.com/projectacrn/acrn-hypervisor/blob/master/.travis-dockerfiles/Dockerfile.clearlinux:
http.sslVerify is forced to be false.
That could introduce the security concern.
Please remove it and try different workaround:
Solution#1: (that will use the Clearelinux auto-proxy)
$ unset https_proxy

Solution#1:
 $ export https_proxy=http://<proxy>:913/

Solution#3:
$ git clone https://.... 
==>
$ git clone http://

**Comment by jren1** [comment] 2018-07-11 04:51
@gvancuts Please review the fix: https://github.com/projectacrn/acrn-hypervisor/pull/665

**Comment by gvancuts** [comment] 2018-07-11 09:41
This is a duplicate of #654 , I have submitted a PR (#656) to address this.

**Comment by NanlinXie** [comment] 2018-12-21 08:43
PR merged, close this issue.

**Closed by NanlinXie** 2018-12-21 08:43 UTC
