### ISSUE TITLE
Local variable 'info' maybe referenced before initializing in 'vmsi_remap()'

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3903] opened 2019-10-23 07:18 UTC
@file vmsi.c /static int32_t vmsi_remap(const struct pci_vdev *vdev, bool enable)

fields of  local variable 'info' maybe accessed before initializing:

1) input 'enable' is false

2) call 'ptirq_msix_remap()'

3)  info.pmsi_addr will be used but it was not initialized or set by 'ptirq_msix_remap()'

**Comment by Mingyuan18** [comment] 2019-10-23 07:31
[External_System_ID] ACRN-5361

**Comment by Mingyuan18** [comment] 2019-11-07 09:11
Close this issue due to no regression issue.

**Closed by Mingyuan18** 2019-11-07 09:11 UTC
Labels: priority: P2-High, type: bug
