### ISSUE TITLE
ACRN debug version build fail for board which doesn't have serial port

### ISSUE THREAD

**Issue by fuzhongl** [projectacrn/acrn-hypervisor#7313] opened 2022-04-19 09:11 UTC
**Describe the bug**

**Platform**
TGLNUC without serial port

**Codebase**
V2.7 or master

**Scenario**
Shared

**To Reproduce**
Build debug version fail for board which doesn't have serial port.
That error was: “lib.error.ResourceError: ttyS0 is not in the native environment! The ttyS available are: dict_keys([])”

**Comment by gvancuts** [comment] 2022-04-19 09:16
Duplicate of #7069

**Closed by gvancuts** 2022-04-19 09:16 UTC
Labels: status: new
