### ISSUE TITLE
enable CAT feature on tgl-rvp on v2.5

### ISSUE THREAD

**Issue by mgcao** [projectacrn/acrn-hypervisor#6547] opened 2021-09-08 08:09 UTC
for TGL-U CAT feature is released now, enable it on release-2.5, so customer can use it easily.

**Comment by wenlingz** [comment] 2021-09-09 01:22
@mgcao please add JIRA ID, thanks

**Comment by mgcao** [comment] 2021-09-09 01:36
[External_System_ID] ACRN-7393

**Comment by NanlinXie** [comment] 2022-03-24 13:12
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:12 UTC
