### ISSUE TITLE
[SIT][ISD][Zephyr] Launch Zephyr will take about 5 mins

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#2974] opened 2019-04-18 08:27 UTC
*Environment*
ClearLinux Version: 28720

*HW/Board*

ISD

*Build link*

N/A

*Steps*

1. Build Zephyr image by follow the guide on https://projectacrn.github.io/latest/tutorials/using_zephyr_as_uos.html?highlight=zephyr
2. Copy the "Zephyr.img", "OVMF.fd" and "launch_zephyr.sh" to ISD 
3. execute the launch_zephyr.sh script

*Expected result*
1. zephyr could boot up successfully and in a short time

*Actual result*
1. zephyr will take about 5 mins to boot up

*Reproduce rate*

Always

*Debugging info*

----

**Comment by Mingyuan18** [comment] 2019-04-18 08:27
[External_System_ID] ACRN-3416

**Comment by gvancuts** [comment] 2019-06-05 09:10
I'm not able to reproduce this on a KBL NUC using the latest code, is this still an issue?

*Note:* you need to use the latest version of Zephyr (that includes this commit https://github.com/zephyrproject-rtos/zephyr/commit/57728ffb276e1c3c6fe0090f7f387a997c605c64) in order to build Grub in a Clear Linux environment.

**Comment by Mingyuan18** [comment] 2019-06-12 06:39
Close with Won't fix.

**Comment by gvancuts** [comment] 2019-06-27 09:23
I still cannot reproduce this with the launch script that we have in the repo, but this is still an issue when you use try to run it as an RTVM. I'll include an example of such a problematic launch script later. In that case, it's known that a different version of Grub works correctly (but nobody has been able to tell yet which exactly :-))

**Comment by gvancuts** [comment] 2019-06-27 09:23
Re-opening

**Comment by fuzhongl** [comment] 2019-07-19 07:13
@gvancuts Any update?
Since this issue isn't ACRN related; we will close it with transferred if no feedback within two weeks.
Thanks for your understanding!

**Comment by gvancuts** [comment] 2019-08-26 16:52
Where would you like to transfer it to?

**Comment by fuzhongl** [comment] 2019-08-26 22:47
@gvancuts Just transfer it to MOSE team, let them know this issue.

**Closed** 2019-10-30 06:46 UTC
Labels: priority: P2-High, type: bug
