### ISSUE TITLE
SOS_LTP_syscalls result is different with native

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3503] opened 2019-07-31 05:22 UTC
**Environment:**
- Board:  KBL NUC
- Clear Linux version:  29880
- ACRN Tag:  acrn-2019w23.4-140000p
- Test Scenario:   Zephyr + SOS + Laag.

**Reproduce step:**
- Prepare the LTP tool

1. Boot to SOS
2. tar -zxf ltp0515installedoptltp.tar.gz -C /
3. cd /opt/ltp
4. ./runltp -p -l syscalls -g syscalls.html -f syscalls.

**result:**
SOS_LTP_syscalls result is different with native

**Repetition rate**
- 100%

**Comment by lirui34** [comment] 2019-07-31 05:22
[External_System_ID] ACRN-4112

**Comment by Mingyuan18** [comment] 2019-10-23 07:23
sendfile09 is caused by no memory, won't fixed this issue.

**Closed by Mingyuan18** 2019-10-23 07:23 UTC
Labels: priority: P2-High, type: bug
