### ISSUE TITLE
Counter in sched_event does not correctly reflect the number of vcpu_make_request

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6502] opened 2021-08-26 09:14 UTC
When BSP vcpu_make_request, if AP is not up, then the counter of that event (event->nqueued) will not increase, whereas in signal_event, the counter will decrease.

**Comment by NanlinXie** [comment] 2022-03-24 13:13
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:13 UTC
Labels: status: new
