### ISSUE TITLE
Refine system shutdown

### ISSUE THREAD

**Issue by wuxyintel** [projectacrn/acrn-hypervisor#6652] opened 2021-10-05 02:48 UTC
Use socket(virtio-net) or vUART for communication between the host and guest side lifecycle managers. Need to update lifecycle manager. Lifecycle manager is a reference implementation, customer can implement more functions (such as shutdown request authority) according to their requirements.
Need to update hypervisor and config tool to support multi legacy vUART. The total number of vUART supported by hypervisor is  8.

Doc Impact Analysis: 

- [x] New feature -> new HLD and usage guide
- [ ] [HLDs](https://projectacrn.github.io/2.3/developer-guides/hld/index.html)
- [ ] [Configuration data](https://projectacrn.github.io/2.3/tutorials/acrn_configuration_tool.html)
- [ ] [Kernel module parameters](https://projectacrn.github.io/2.3/user-guides/kernel-parameters.html)
- [ ] [Device Model (acrn-dm) parameters](https://projectacrn.github.io/2.3/user-guides/acrn-dm-parameters.html)
- [ ] [Hypervisor shell commands](https://projectacrn.github.io/2.3/user-guides/acrn-shell.html)
- [ ] [ACRN tools (debug and/or service)](https://projectacrn.github.io/2.3/develop.html#configuration-and-tools)
- [ ] [Build system](https://projectacrn.github.io/latest/getting-started/building-from-source.html)
- [ ] [Other documents (e.g. tutorials)](https://projectacrn.github.io/2.3/develop.html#enable-acrn-features)

**Comment by yuchuyang** [comment] 2021-10-08 01:53
[External_System_ID] ACRN-7407

**Comment by NanlinXie** [comment] 2021-11-24 03:31
Updated document:
https://projectacrn.github.io/latest/tutorials/enable_s5.html
https://projectacrn.github.io/latest/getting-started/getting-started.html

**Comment by amyreye** [comment] 2022-02-17 03:42
@NanlinXie @dbkinder Can we close this issue?

**Comment by NanlinXie** [comment] 2022-03-24 13:11
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:11 UTC
Labels: doc: done
