### ISSUE TITLE
[TGL][RTCT]Input/output error happened when list acpi/tables directory after enabled RTCT in pre-rt

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#6303] opened 2021-07-16 03:16 UTC
*Environment*

 HV branch ： Rlease_2.5

*Steps:*
 git clone acrn-hypervisor and check out to release_2.5
 Copy RTCT from board to ./misc/config_tools/acpi_template/tgl-rvp/RTCT
 enabled SSRAM in  hybrid_rt scenario file and build HV
 replace image on board and boot pre-rt and SOS
 list file in acpi/tables in pre-rt (ls /sys/firmware/acpi/tables/)

 

*Expected result*
 list acpi/table normally

*Actual result*

Input/output error happened when list acpi/tables

  

*Note:* not find the issue if disable ssram 

*Debugging info*

  root@intel-corei7-64:/# ls /sys/firmware/acpi/tables/
  ls: reading directory '/sys/firmware/acpi/tables/': Input/output error

**Comment by Kunhui-Li** [comment] 2021-07-16 03:19
[External_System_ID] ACRN-7273

**Comment by NanlinXie** [comment] 2022-03-24 13:18
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:18 UTC
Labels: status: new
