### ISSUE TITLE
doc: Update ACRN-specific coding style exceptions with regard to Linux style

### ISSUE THREAD

**Issue by junjiemao1** [projectacrn/acrn-hypervisor#1557] opened 2018-10-23 01:39 UTC
ACRN mostly follows Linux coding style, but with a few exceptions for, e.g. MISRA-C compliance. The checkpatch.pl script shall be customized before applying to the ACRN code so that warnings on such exceptions are suppressed.

**Comment by dbkinder** [comment] 2019-02-28 20:26
@junjiemao1 @NanlinXie @lijinxia @hwang37 Can we close this issue as fixed now?

**Comment by eternalNight** [comment] 2019-03-01 00:40
@dbkinder I think so. The customized configuration to checkpatch has been merged months ago.

@NanlinXie Would you please verify and close this issue? Thanks.

**Comment by junjiemao1** [comment] 2019-03-01 00:41
@dbkinder I think so. The customized configuration to checkpatch has been merged months ago.

@NanlinXie Would you please verify and close this issue? Thanks.

**Comment by dbkinder** [comment] 2019-03-22 14:06
We're also maintaining a [coding style doc](https://projectacrn.github.io/latest/developer-guides/coding_guidelines.html) now, so the issue is resolved.

**Closed by dbkinder** 2019-03-22 14:06 UTC
Labels: area: documentation
