### ISSUE TITLE
[Task] Configuration tool and data refine and clean up.

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#6315] opened 2021-07-21 12:10 UTC
Clear up configtool obsolete kconfig and board.xml files

1. Remove Kconfig
2. Move board.xml into 1source. (1- adl-rvp, 2- ehl-crb-b, 3-tgl-rvp) 
    Overall solution discussion
    moving files to 1source.
3. Clean up scenario python script, remove the obsolete files that already been replaced by xsl.
4. Add revision for board.xml and scenario.xml files(schema file) - TBD
    Define the notation of revision.  1->2 .... 
    Apply to all board.xml and scenario.xml files: attribute: "schema_version"
    Define the rule to update the revision: board.xml , scenario.xml files(schema file)
5. Clean up sample launch script. - libvirt direction - TBD
6. Change the scenario name as shared/partitioned/hybrid
7. Update launch xml for only one NVME

**Comment by Kunhui-Li** [comment] 2021-07-21 13:49
[External_System_ID] ACRN-7263

**Comment by NanlinXie** [comment] 2022-03-24 13:17
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:17 UTC
