### ISSUE TITLE
set realtime sched policy for vcpu thread (apl_sdc_stable)

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2717] opened 2019-03-11 02:18 UTC
To reduce the io emulation impact to audio FE which could trigger audio glitch

**Comment by mwang106** [comment] 2019-03-11 02:19
[External_System_ID] ACRN-2941

**Comment by Mingyuan18** [comment] 2019-03-18 02:58
Can't reproduce this issue in below build, So close it.
ACRN TAG:  2019w11.3.153000p
Kernel: 4.19.23-24
SOS: 28100

**Closed by Mingyuan18** 2019-03-18 02:58 UTC
Labels: status: implemented, type: bug
