### ISSUE TITLE
Enable SMBios & TPM2 Event Log for TGL

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#6320] opened 2021-07-23 06:55 UTC
release 2.5 request SMBios & dTPM event log supprot on TGL

**Comment by taoyuhong** [comment] 2021-07-23 06:56
[External_System_ID] ACRN-6527

**Comment by NanlinXie** [comment] 2022-03-24 13:17
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:17 UTC
