### ISSUE TITLE
[config-tools] Some files need to be well maintained by board_inspector/UI and build script

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#6238] opened 2021-06-22 08:17 UTC
1. There are some files under acpi_template are confusing.
2. Need enable cp file into board_inspector folder.

**Comment by Kunhui-Li** [comment] 2021-06-22 08:18
[External_System_ID] ACRN-7248

**Comment by NanlinXie** [comment] 2022-03-24 13:20
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:20 UTC
Labels: status: new
