### ISSUE TITLE
Pre-launched VM Boot from ELF

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#6323] opened 2021-07-26 03:13 UTC
The hypervisor shall support boot pre-launched VM with kernel image of ELF type, the hypervisor shall parse ELF header to load the kernel image and launch it from correct entry point.

This support shall be configurable.

**Comment by NanlinXie** [comment] 2021-07-26 03:17
[External_System_ID] ACRN-7310

**Comment by NanlinXie** [comment] 2021-07-26 07:51
Doc Impact Analysis: 

- [ ] New feature -> new HLD and usage guide
- [ ] [HLDs](https://projectacrn.github.io/2.3/developer-guides/hld/index.html)
- [ ] [Configuration data](https://projectacrn.github.io/2.3/tutorials/acrn_configuration_tool.html)
- [ ] [Kernel module parameters](https://projectacrn.github.io/2.3/user-guides/kernel-parameters.html)
- [x] [Device Model (acrn-dm) parameters](https://projectacrn.github.io/2.3/user-guides/acrn-dm-parameters.html)
- [ ] [Hypervisor shell commands](https://projectacrn.github.io/2.3/user-guides/acrn-shell.html)
- [ ] [ACRN tools (debug and/or service)](https://projectacrn.github.io/2.3/develop.html#configuration-and-tools)
- [ ] [Build system](https://projectacrn.github.io/latest/getting-started/building-from-source.html)
- [ ] [Other documents (e.g. tutorials)](https://projectacrn.github.io/2.3/develop.html#enable-acrn-features)

**Comment by NanlinXie** [comment] 2021-07-26 07:53
The "Other documents" means "[Getting Started Guide for ACRN Hybrid Mode](https://projectacrn.github.io/latest/tutorials/using_hybrid_mode_on_nuc.html)"

**Comment by gvancuts** [comment] 2021-07-26 08:33
This section in our documentation should also be updated accordingly: https://github.com/projectacrn/acrn-hypervisor/blob/master/doc/introduction/index.rst#boot-sequence

**Comment by jsun26intel** [comment] 2021-07-26 09:53
@gvancuts Why? The issue is just related to pre-launched VM kernel image format.

**Comment by gvancuts** [comment] 2021-07-26 13:23
> @gvancuts Why? The issue is just related to pre-launched VM kernel image format.

Oh yes, my bad. So there is no change whatsoever to how we boot ACRN using EFI?

**Comment by jsun26intel** [comment] 2021-07-26 14:27
just make sure the packed prelaunched zephyr image format is in elf format.

**Comment by amyreye** [comment] 2022-02-17 03:44
@NanlinXie @dbkinder Can we close this issue?

**Closed** 2022-03-04 01:56 UTC
Labels: status: new, doc: done
