### ISSUE TITLE
ACPI NVS region might not be mapped on prelaunched-VM

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6423] opened 2021-08-18 07:09 UTC
In hypervisor codebase there is an assumption that ACPI NVS/Data region for pre-launched VM is at most 1M. This assumption is no longer true since recent patches to enlarge the ACPI NVS region. As a result the ACPI NVS region might not be mapped because the remaining_hpa_size (arch/x86/guest/vm.c, prepare_prelaunched_vm_memmap) is not large enough.

**Comment by yfliuuu** [comment] 2021-08-18 07:10
[External_System_ID] ACRN-7346

**Comment by NanlinXie** [comment] 2022-03-24 13:14
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:14 UTC
Labels: status: new
