### ISSUE TITLE
System:  UOS crash leads to system reboot

### ISSUE THREAD

**Issue by ailun258** [projectacrn/acrn-hypervisor#1004] opened 2018-08-12 06:55 UTC
1, setup SOS and UOS following Getting started guide
2, installed desktop bundle in UOS
3, start gdm desktop : systemctl start gdm
4, copy any 1080P video file into UOS /home/user/Video
5,  open file manager. go into /home/user/Video
6,  open this 1080P video.  playback with totem player,  

result:  after several mints, UOS crashed, and whole the system reboot automatically 
expect:  UOS reboot only, it should not impact SOS.

**Comment by xiaoxiax** [comment] 2018-12-26 03:19
Cannot reproduced this issue with gst-launch-1.0 tool.
Please help to close it, thanks!

**Closed** 2018-12-26 06:16 UTC
