### ISSUE TITLE
TPM pass-thru shall be able to support start method 6, not only support Start Method of 7

### ISSUE THREAD

**Issue by lifeix** [projectacrn/acrn-hypervisor#6366] opened 2021-08-09 06:22 UTC
[External_System_ID] ACRN-7097

**Comment by wenlingz** [comment] 2021-08-09 07:43
[External_System_ID] ACRN-7097

**Comment by NanlinXie** [comment] 2022-03-24 13:15
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:15 UTC
