### ISSUE TITLE
Refine the vPCI code for virtual bar emulation

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#6011] opened 2021-05-14 03:29 UTC
vPCI Code Refine

Boot HV, lots of HV warnings print as below:
pci_vdev_update_vbar_base reprogram PCI:00:15.0 BAR0 to addr:0x607d4e8000, which is out of mmio window[0x0 - 0x0]0
pci_vdev_update_vbar_base reprogram PCI:00:15.1 BAR0 to addr:0x607d4e7000, which is out of mmio window[0x0 - 0x0]0

**Comment by taoyuhong** [comment] 2021-05-14 03:30
[External_System_ID] ACRN-6924

**Comment by gvancuts** [comment] 2021-06-03 08:59
Can you also put in this issue the logs showing the problem. I _think_ this is what I saw running ACRN v2.5 on QEMU but it would be good to confirm this by comparing the log output.

**Comment by taoyuhong** [comment] 2021-06-04 02:08
> Can you also put in this issue the logs showing the problem. I _think_ this is what I saw running ACRN v2.5 on QEMU but it would be good to confirm this by comparing the log output.

Updated

**Comment by NanlinXie** [comment] 2022-03-24 13:22
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:22 UTC
