### ISSUE TITLE
ACRN build improvement

### ISSUE THREAD

**Issue by liuhang-bit** [projectacrn/acrn-hypervisor#6355] opened 2021-08-05 06:30 UTC
User could use make targz-pkg command to generate tar package in
build directory,which could help user simplify the process
of installing acrn hypervisor in target board. user need to copy the
tarball package to target board,and extract it to "/" directory.

**Comment by liuhang-bit** [comment] 2021-08-05 06:31
[External_System_ID] ACRN-7322

**Comment by NanlinXie** [comment] 2022-03-24 13:16
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:16 UTC
