### ISSUE TITLE
Cannot boot to 5.10 sos on ADL

### ISSUE THREAD

**Issue by shuox** [projectacrn/acrn-hypervisor#6006] opened 2021-05-13 02:14 UTC
TPAUSE, UMONITOR or UMWAIT instructions execution in guest VM cause
    a #UD if "enable user wait and pause" (bit 26) of VMX_PROCBASED_CTLS2
    is not set. To fix this issue, set the bit 26 of VMX_PROCBASED_CTLS2.

**Comment by shuox** [comment] 2021-05-13 02:15
[External_System_ID] ACRN-7066

**Comment by NanlinXie** [comment] 2022-03-24 13:22
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:22 UTC
Labels: status: new
