### ISSUE TITLE
HV: enable #GP for guest uc-lock 

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#6299] opened 2021-07-15 05:34 UTC
The hypervisor shall present a virtual UC lock capability to the guest, and directly deliver #GP to guest. Virtual UC lock capability helps the guest to isolate violations from user land. Guest write of MSR_TEST_CTL is ignored, guest read gets the written value.

**Comment by taoyuhong** [comment] 2021-07-15 05:35
[External_System_ID] ACRN-6637

**Comment by NanlinXie** [comment] 2022-03-24 13:19
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:19 UTC
