### ISSUE TITLE
Succeed to reboot the whole system while execute reboot command in SOS

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3505] opened 2019-07-31 07:10 UTC
**Steps:**
1. Boot up SOS, and pre-launched Zephyr guest also boot up automatically.
2. Execute "./launch_uos.sh" to boot up LaaG.
3. Connect with $SOS_IP and reboot SOS.
4. Wait 30 seconds for platform shutdown and boot again.

**Expected behavior:**
Cannot reboot the whole system while execute ``reboot`` command in SOS.
Only execute ``reboot`` command in pre-launched Zephyr guest to reboot the whole system.

**Comment by lirui34** [comment] 2019-07-31 07:10
[External_System_ID] ACRN-4083

**Comment by Mingyuan18** [comment] 2019-08-07 02:24
Cannot reproduce this issue use below build, so close it.
ClearLinux version: 30580
ACRN tag: acrn-2019w31.3-140000p
HW: KBLNUC DNHi7

**Closed by Mingyuan18** 2019-08-07 02:24 UTC
Labels: priority: P2-High, type: bug
