### ISSUE TITLE
hv: SMBIOS passthrough: UEFI environment checks should be added before probing

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6345] opened 2021-08-02 06:26 UTC
Previously SMBIOS passthrough assumes UEFI environment but this may cause problems on non-UEFI environment. Checks should be added before probing SMBIOS table.

**Comment by yfliuuu** [comment] 2021-08-02 06:38
[External_System_ID] ACRN-6527

**Comment by NanlinXie** [comment] 2022-03-24 13:16
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:16 UTC
Labels: status: new
