### ISSUE TITLE
DMAR_PARSE_ENABLED fails on few platforms

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2320] opened 2019-01-12 08:40 UTC
when DMAR_PARSE_ENABLED is set to true, hypervisor crashes on certain platforms. For example, apl-MRB.

**Comment by Mingyuan18** [comment] 2019-01-14 02:51
[External_System_ID] ACRN-2462

**Comment by Mingyuan18** [comment] 2019-01-17 06:33
@sainath14 , 
Please confirm if this bug still exists. If can't be reproduced. Please close it.

**Comment by Mingyuan18** [comment] 2019-04-11 06:54
Can't reproduce this issue in below build, so close it.
SOS: 28720
ACRN TAG: acrn-2019w15.3-140000f

**Closed by Mingyuan18** 2019-04-11 06:54 UTC
Labels: status: Assigned, type: bug
