### ISSUE TITLE
HDMI2 Video cannot Full-screen playback in clone mode

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1201] opened 2018-09-10 06:18 UTC
SW Version Latest#2150-S
Kernel Version / Android Version 4.14.61-quilt-2e5dc0ac-g2692c1627a96 / 9
SBL IFWI Version SBL_APL_ACRN_1_0_2_114
IOC Version 4. 0. 2

SOS Kernel Version 4.14.61-76.pk414-sos #1 SMP PREEMPT Wed Aug 8
SOS Version Installed version: 24330
Hypervisor version HV version 0.2-unstable-2018-08-09
Step 1, content two HDMI and eDP
Step 2, Boot UOS
Step 3, Open gallery
Step 4, Select one Video file and play it
Step 5, Pause/Play the Video
Step 6, Observe screen after finish playback.
----------------------------------------------------------------------------
*Expected Results:
Step 4, Video play well
*Actual Results:
step 4, gallery cannot Full-screen playback
step 6, Black screen displays for 0.5min after finish playback the some videos
video type : h263,h264,mp4,vp8,vp9

**Comment by dandanyx** [comment] 2018-10-16 05:56
Cannot reproduce this issue on WW42 AaaG build, and suggest to close this issue, thanks!

**Closed** 2018-10-16 05:57 UTC
Labels: status: open, type: bug
