### ISSUE TITLE
Service VM shall not have capability to access IOMMU

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6677] opened 2021-10-15 07:47 UTC
The IOMMU is actually owned by hypervisor, while its MMIO is not blocked for service VM.

Requirements:
1. Service VM need to access native ACPI table fully, hence can't not hide dmar in ACPI table of Service VM.
2. Need to block Service VM from accessing dmar hardware even it can be detected in ACPI table.
3. there is no such restriction on pre-launched & post launched VM.

**Comment by NanlinXie** [comment] 2022-03-24 13:11
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:11 UTC
Labels: status: new
