### ISSUE TITLE
hv: remove registration of default port IO and MMIO handlers

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3904] opened 2019-10-23 07:25 UTC
The default behaviors of PIO & MMIO handlers are same for all VMs, no need to expose dedicated APIs to register default hanlders.

**Comment by Mingyuan18** [comment] 2019-10-23 07:34
[External_System_ID] ACRN-5506

**Comment by Mingyuan18** [comment] 2019-11-07 09:09
Close this issue due to no regression found.

**Closed by Mingyuan18** 2019-11-07 09:09 UTC
Labels: priority: P2-High, type: bug
