### ISSUE TITLE
Support X86_TEE

### ISSUE THREAD

**Issue by ssqre** [projectacrn/acrn-hypervisor#6571] opened 2021-09-15 02:17 UTC
[External_System_ID] ACRN-7399

**Comment by ssqre** [comment] 2021-09-15 02:29
ACRN supports X86_TEE which can emulate the ARM TrustZone on x86 architecture

1. priority based scheduler support
2. TEE VM (X86 OPTEE) boot support, TEE VM memmap support
3. TEE and REE hypercall support
4.  Interrupt flow  Support

**Comment by wenlingz** [comment] 2021-09-18 08:21
[External_System_ID] ACRN-7399

**Comment by dbkinder** [comment] 2022-01-26 19:17
@NanlinXie @ssqre What's the status of this, and is documentation needed?

**Comment by NanlinXie** [comment] 2022-03-24 13:12
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:12 UTC
Labels: doc: needed
