### ISSUE TITLE
OVMF release v3.0

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#7231] opened 2022-03-30 09:24 UTC
OVMF release v3.0

- VGA interface of virtio-gpu adapter support
- Ovmf:ACRN: Fix the building error
- acrn: fix how to get memory below 4G

**Comment by NanlinXie** [comment] 2022-04-11 11:32
Closed since patch merged with no regression.

**Closed by NanlinXie** 2022-04-11 11:32 UTC
Labels: status: new
