### ISSUE TITLE
Failure to check the alignment of software SRAM regions

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6778] opened 2021-11-04 09:45 UTC
the address of  boundaries of software SRAM shall be page-aligned,  DM shall check for this to avoid any violations.

**Comment by yonghuah** [comment] 2021-11-04 09:45
[External_System_ID] ACRN-7477

**Comment by NanlinXie** [comment] 2022-03-24 13:09
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:09 UTC
Labels: status: new
