### ISSUE TITLE
memory leakage issue in acrn_parse_cpu_affinity

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6919] opened 2021-11-30 01:50 UTC
Memory pointer by 'cp' shall be freed.

**Comment by yonghuah** [comment] 2021-11-30 01:50
[External_System_ID] ACRN-7392

**Comment by NanlinXie** [comment] 2022-03-24 13:08
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:08 UTC
Labels: status: new
