### ISSUE TITLE
hv: debug: enable hv console when lapic-pt is enabled on BSP

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6312] opened 2021-07-21 06:01 UTC
In some scenarios (e.g., nested) where lapic-pt is enabled for a vcpu running on a pcpu hosting console timer, the hv console will be inaccessible. The console can be re-enabled by hooking the callback into every VM-exit event.

**Comment by yfliuuu** [comment] 2021-07-21 07:25
[External_System_ID] ACRN-7305

**Comment by NanlinXie** [comment] 2022-03-24 13:17
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:17 UTC
