### ISSUE TITLE
Make ACRN builds reproducible

### ISSUE THREAD

**Issue by tttech-industrial-buchsbaum** [projectacrn/acrn-hypervisor#6035] opened 2021-05-19 17:41 UTC
Due to using 'date' command during build and not supporting SOURCE_DATE_EPOCH as recommended at https://reproducible-builds.org/ ACRN builds are not reproducible. Most build and packaging systems require a build to be reproducible. So a first step will be supporting SOURCE_DATE_EPOCH and the possibility to set all items that are part of generated files.

**Comment by wenlingz** [comment] 2021-05-20 01:00
[External_System_ID] ACRN-6381

**Comment by NanlinXie** [comment] 2022-03-24 13:21
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:21 UTC
Labels: status: new
