### ISSUE TITLE
Script: Fix snd_soc_skl typo in launch script (apl_sdc_stable)

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#2666] opened 2019-03-02 11:32 UTC
Fix snd-soc-skl to snd_soc_skl in launch script.

**Comment by wenlingz** [comment] 2019-03-05 08:53
[External_System_ID]ACRN-2889

**Comment by Mingyuan18** [comment] 2019-03-25 05:07
Can't reproduce this issue in below build, so close it.
ACRN-Hypervisor : 2019w10.4.150000p_164
SOS: 28104

**Closed by Mingyuan18** 2019-03-25 05:07 UTC
Labels: priority: P2-High, status: Assigned, type: bug
