### ISSUE TITLE
ICX-D LCC bring-up

### ISSUE THREAD

**Issue by ylian16** [projectacrn/acrn-hypervisor#6357] opened 2021-08-05 09:28 UTC
[External_System_ID] ACRN-7244

**Comment by wenlingz** [comment] 2021-08-17 02:03
[External_System_ID] ACRN-7244

**Comment by NanlinXie** [comment] 2021-11-03 02:43
No document needed.

**Comment by NanlinXie** [comment] 2022-03-24 13:15
Closed since patch merged without regression.

**Closed by NanlinXie** 2022-03-24 13:15 UTC
Labels: doc: no doc needed
